#General parameters for the project
CONSUMER_KEY: 'GV8cYa5GSjk27F2JZb6z8MrsJ'
CONSUMER_SECRET_KEY: 'mybd68vqhP6wSyvQOtxlYoc9aRne08FAImpchhL679W2vgNfsS'
ACCESS_TOKEN_KEY: '1085983643640709121-qEMfxY6RSmPHHaEvDxIIsEXSjn2y5v'
ACCESS_TOKEN_SECRET_KEY: 'jZ02dDaFlPNC5gJI5PTuV9BeivolkPlPxcLK8LuAPDEME'